import { config as loadDotenv } from "dotenv";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
export const ACK = "CREATE_AND_DELETE_SYNTHETIC_V23_QA_DATA";
export type QaConfig = { baseUrl:string; baseHost:string; renderHealthUrl:string; expectedCommit:string; clerkPublishableKey:string; clerkSecretKey:string; userAEmail:string; userBEmail:string; supabaseUrl:string; supabaseElevatedKey:string; vercelToken:string; vercelScope?:string; seedMode:"admin"|"ui"; runId:string; manifestPath:string; reportPath:string; resultsPath:string; };
function req(name:string){ const v=process.env[name]?.trim(); if(!v) throw new Error(`Missing required QA configuration: ${name}`); return v; }
function isPublishableSupabaseKey(v:string){ return /^(sb_publishable_|eyJ)/.test(v) && v.length < 260; }
export function loadQaConfig(): QaConfig { const envPath=resolve(process.cwd(), ".env.qa.local"); if(existsSync(envPath)) loadDotenv({path:envPath, override:false}); const tracked=process.env.QA_ENV_TRACKED; if(tracked) throw new Error(".env.qa.local appears to be tracked; refusing to run."); const baseUrl=req("QA_BASE_URL"); const renderHealthUrl=req("QA_RENDER_HEALTH_URL"); const expectedCommit=req("QA_EXPECTED_COMMIT"); const seedMode=(process.env.QA_SEED_MODE?.trim()||"admin") as "admin"|"ui"; if(!baseUrl.startsWith("https://")) throw new Error("QA_BASE_URL must be HTTPS."); if(!renderHealthUrl.startsWith("https://")) throw new Error("QA_RENDER_HEALTH_URL must be HTTPS."); const host=new URL(baseUrl).hostname; if(["localhost","127.0.0.1","::1"].includes(host)) throw new Error("QA_BASE_URL must not resolve to localhost in production mode."); if(process.env.QA_CONFIRM_PRODUCTION_MUTATION !== ACK) throw new Error("QA_CONFIRM_PRODUCTION_MUTATION acknowledgement is missing or incorrect."); const a=req("QA_USER_A_EMAIL"), b=req("QA_USER_B_EMAIL"); if(a.toLowerCase()===b.toLowerCase()) throw new Error("QA users must use different email addresses."); const elevated=(process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY || "").trim(); if(seedMode==="admin" && !elevated) throw new Error("Admin seed mode requires SUPABASE_SECRET_KEY or SUPABASE_SERVICE_ROLE_KEY."); if(elevated && isPublishableSupabaseKey(elevated)) throw new Error("Elevated Supabase credential looks publishable/browser-safe; refusing to run."); const runId=`${new Date().toISOString().replace(/[-:.TZ]/g,"").slice(0,14)}-${Math.random().toString(36).slice(2,8)}`; return { baseUrl, baseHost:host, renderHealthUrl, expectedCommit, clerkPublishableKey:req("CLERK_PUBLISHABLE_KEY"), clerkSecretKey:req("CLERK_SECRET_KEY"), userAEmail:a, userBEmail:b, supabaseUrl:req("SUPABASE_URL"), supabaseElevatedKey:elevated, vercelToken:req("VERCEL_TOKEN"), vercelScope:process.env.VERCEL_SCOPE?.trim()||undefined, seedMode, runId, manifestPath:resolve(process.cwd(),`test-results/version23-manifest-${runId}.json`), reportPath:"/tmp/version23-data-control-qa.md", resultsPath:resolve(process.cwd(),"test-results/version23-results.json")}; }
export function safeConfigSummary(c:QaConfig){ return {baseHost:c.baseHost, renderHealthHost:new URL(c.renderHealthUrl).hostname, expectedCommit:c.expectedCommit, userLabels:["A","B"], seedMode:c.seedMode, vercelScopePresent:Boolean(c.vercelScope)}; }
