import { createClient } from "@supabase/supabase-js"; import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs"; import { dirname } from "node:path"; import type { QaConfig } from "./config";
export type CreatedRecord={id:string; ownerLabel:"A"|"B"; title:string; company:string}; type Manifest={runId:string; records:CreatedRecord[]; cleanupStatus?:"PASS"|"FAIL"};
function admin(c:QaConfig){ return createClient(c.supabaseUrl,c.supabaseElevatedKey,{auth:{persistSession:false,autoRefreshToken:false}}); }
export function readManifest(path:string):Manifest{ if(!existsSync(path)) return {runId:"",records:[]}; return JSON.parse(readFileSync(path,"utf8")); }
function save(c:QaConfig,m:Manifest){ mkdirSync(dirname(c.manifestPath),{recursive:true}); writeFileSync(c.manifestPath,JSON.stringify(m,null,2)); }
export async function resolveClerkUserIds(c:QaConfig){ const headers={Authorization:`Bearer ${c.clerkSecretKey}`}; async function one(email:string){ const r=await fetch(`https://api.clerk.com/v1/users?email_address=${encodeURIComponent(email)}`,{headers}); if(!r.ok) throw new Error(`Unable to resolve Clerk QA user ${r.status}`); const users=await r.json() as Array<{id:string}>; if(users.length!==1) throw new Error("Expected exactly one Clerk QA user for configured email."); return users[0].id; } return {A:await one(c.userAEmail), B:await one(c.userBEmail)}; }
export async function seedAdminRecords(c:QaConfig, uiRecordId?:string){ if(c.seedMode!=="admin") return; const ids=await resolveClerkUserIds(c); const sb=admin(c); const manifest:Manifest={runId:c.runId,records:[]}; if(uiRecordId) manifest.records.push({id:uiRecordId, ownerLabel:"A", title:`V23 QA ${c.runId} UI saved analysis`, company:"Version 23 QA Company"}); for(const label of ["A","B"] as const){ const count=label==="A"?23-(uiRecordId?1:0):1; for(let i=0;i<count;i++){ const n=String(i+1).padStart(2,"0"); const title=`V23 QA ${c.runId} ${label} ${n}${i===15?" older-pagination-search-target":""}`; const notes=i===2?'Follow up, high priority':i===3?'Contact said "review next week"':i===4?'Has notes':'no notes'; const created_at=new Date(Date.now()-(label==="A"?i:50)*60000).toISOString(); const run=await sb.from("analysis_runs").insert({clerk_user_id:ids[label],run_label:`V23 QA ${c.runId}`,created_at}).select("id").single(); if(run.error) throw run.error; const job=await sb.from("job_analyses").insert({analysis_run_id:run.data.id,clerk_user_id:ids[label],job_title:title,company:"Version 23 QA Company",source_url:`https://example.invalid/v23/${c.runId}/${label}/${n}`,notes,matched_skills_count:2,missing_skills_count:i%2===0?2:0,created_at}).select("id").single(); if(job.error) throw job.error; await sb.from("matched_skills").insert([{job_analysis_id:job.data.id,clerk_user_id:ids[label],skill:"excel",category:"business"},{job_analysis_id:job.data.id,clerk_user_id:ids[label],skill:"logistics",category:"operations"}]); if(i%2===0) await sb.from("skill_gaps").insert([{job_analysis_id:job.data.id,clerk_user_id:ids[label],skill:"forecasting",category:"operations"},{job_analysis_id:job.data.id,clerk_user_id:ids[label],skill:"sap erp",category:"business"}]); manifest.records.push({id:job.data.id,ownerLabel:label,title,company:"Version 23 QA Company"}); save(c,manifest); } } }
export async function cleanupCurrentRun(c:QaConfig){ const m=readManifest(c.manifestPath); const ids=await resolveClerkUserIds(c); const sb=admin(c); let ok=true; for(const r of m.records){ const owner=ids[r.ownerLabel]; const {error}=await sb.from("job_analyses").delete().eq("id",r.id).eq("clerk_user_id",owner).eq("company","Version 23 QA Company").like("job_title",`V23 QA ${c.runId}%`); if(error){ ok=false; console.error(`Cleanup failed for synthetic ${r.ownerLabel} ${r.id} ${r.title}`); } } const remaining=await sb.from("job_analyses").select("id,job_title,company").in("id",m.records.map(r=>r.id)); if(remaining.error || (remaining.data?.length||0)>0) ok=false; save(c,{...m,cleanupStatus:ok?"PASS":"FAIL"}); if(!ok) throw new Error(`Cleanup failed. Safe retry: npm run qa:version23:cleanup -- --run-id ${c.runId}`); }
export async function dryRunStaleCleanup(){ console.log("Dry run only. Stale cleanup is limited to configured QA users, Version 23 QA Company, and V23 QA titles."); }
