# Import Path so this file can work with file paths.
from pathlib import Path


# This helper function turns a list of skills into markdown bullet points.
def format_skill_list(skills):

    # If the list is empty, return a simple message.
    if not skills:
        return "- None found\n"

    # Create an empty string that we will build up line by line.
    skill_text = ""

    # Loop through each skill in the list.
    for skill in skills:

        # Add one markdown bullet line for each skill.
        skill_text += f"- {skill}\n"

    # Return the finished bullet list.
    return skill_text


# This helper function turns recurring gap results into markdown bullets.
def format_recurring_gaps(recurring_gaps):

    # If there are no recurring gaps, return a simple message.
    if not recurring_gaps:
        return "- No gaps found\n"

    # Create an empty string that we will build up line by line.
    gap_text = ""

    # Loop through each recurring gap.
    for gap in recurring_gaps:

        # Add one markdown bullet with the skill, category, and count.
        gap_text += f"- {gap['gap_skill']} ({gap['category']}): {gap['count']} job(s)\n"

    # Return the finished recurring gaps text.
    return gap_text


# This function writes the final gap report.
#
# It needs:
# 1. output_path: where the report should be saved
# 2. resume_skills: skills found in the resume
# 3. job_results: a list containing the results for each job description
# 4. recurring_gaps: a sorted list of the most repeated skill gaps
def write_gap_report(output_path, resume_skills, job_results, recurring_gaps):

    # Convert output_path into a Path object.
    output_path = Path(output_path)

    # Make sure the output folder exists.
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Create an empty list to store each line/section of the report.
    lines = []

    # Add the main title of the markdown report.
    lines.append("# Internship Fit & Skill-Gap Report\n\n")

    # Add a short note explaining what this report is.
    lines.append("This report was generated by the pure-Python Version 1 analyzer.\n\n")

    # Add the recurring gaps section near the top.
    lines.append("## Most Common Skill Gaps\n\n")
    lines.append(format_recurring_gaps(recurring_gaps))
    lines.append("\n")

    # Add the resume skills section.
    lines.append("## Skills Found in Resume\n\n")

    # Loop through each skill category found in the resume.
    for category, skills in resume_skills.items():

        # Add the category name as a markdown heading.
        lines.append(f"### {category}\n\n")

        # Add the skills for that category as bullet points.
        lines.append(format_skill_list(skills))

        # Add a blank line between sections.
        lines.append("\n")

    # Add the job analysis section.
    lines.append("## Job Analyses\n\n")

    # Loop through each job result.
    for job_result in job_results:

        # Add the job file name as a heading.
        lines.append(f"### {job_result['job_name']}\n\n")

        # Add a section for skills found in the job.
        lines.append("#### Skills Found in Job\n\n")

        # Loop through the skill categories for this job.
        for category, skills in job_result["job_skills"].items():

            # Add the category name.
            lines.append(f"##### {category}\n\n")

            # Add the skills found in this category.
            lines.append(format_skill_list(skills))

            # Add a blank line.
            lines.append("\n")

        # Add a section for gaps.
        lines.append("#### Skill Gaps\n\n")

        # Loop through each skill gap category.
        for category, gaps in job_result["skill_gaps"].items():

            # Add the category name.
            lines.append(f"##### {category}\n\n")

            # Add the missing skills for this category.
            lines.append(format_skill_list(gaps))

            # Add a blank line.
            lines.append("\n")

    # Combine all report lines into one big string.
    report_text = "".join(lines)

    # Write the report text into the markdown file.
    output_path.write_text(report_text, encoding="utf-8")
